---
- hosts: magnoliademo
  become: yes
  become_user: root
  tasks:

  - name: Deploying magnolia-cms default
    docker_container:
      name: magnolia-demo-default
      image: calem15/magnolia-demo:default
      restart_policy: always
      state: started
      pull: true
      recreate: yes
      published_ports:
        - 8280:8080