---
- hosts: magnoliademo
  become: yes
  become_user: root
  tasks:
  - name: Installing configuration for prometheus
    template: src=prometheus/prometheus.yml dest=/data/prometheus/prometheus.yml owner=root group=root

  - name: Deploying prometheus
    docker_container:
      name: prometheus
      image: prom/prometheus
      restart_policy: always
      state: started
      pull: true
      recreate: yes
      published_ports:
        - 9090:9090
      volumes:
        - /data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  - name: Deploying grafana
    docker_container:
      name: grafana
      image: prom/prometheus
      restart_policy: always
      state: started
      pull: true
      recreate: yes
      published_ports:
        - 3000:3000
